// <auto-generated />
namespace styleBarber.Wep.ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _init2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_init2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005260836486__init2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
